### ISSUE TITLE
[Bug]: Double render with React.StrictMode

### ISSUE THREAD

**Issue by OlegKipchatov** [VKCOM/vkid-web-sdk#12]
### Описание

При включенном React.StrictMode рендер кнопки VKID происходит два раза

### Шаги воспроизведения

``` tsx
'use client'

import { useLayoutEffect } from "react";
import * as VKID from '@vkid/sdk';

export default function Component() {
    useLayoutEffect(() => {
        VKID.Config.set({
            app: app_id,
            redirectUrl: redirect_url,
        });

        const oneTap = new VKID.OneTap();
        oneTap.render({
            container: document.getElementById('vk-oauth') as HTMLElement,
        });
    }, []);

    return(
        <div className="my-4 flex justify-center">
            <div id='vk-oauth'></div>
        </div>
    );
}
```

### Версия vkid/sdk

1.1.0

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

### Ожидаемое поведение

Компонент отрендерится один раз

### Скриншоты

<img width="692" alt="image" src="https://github.com/VKCOM/vkid-web-sdk/assets/35765711/c684a4f4-b31e-4070-9290-3902d1a32017">

**Comment by mclaran** [comment]
@OlegKipchatov привет! Данное поведение не является следствием неправильной работы sdk.
При использовании StrictMode из React, эффекты намерено вызываются дважды, чтобы помочь найти ошибки, вызванные отсутствием очистки эффектов (см [документацию](https://react.dev/reference/react/StrictMode)).

В Вашем случаи как раз найдена данная ошибка, чтобы избежать поведения с двойным рендером, необходимо вызвать функцию очистки:
`
    useLayoutEffect(() => {
        VKID.Config.set({
            app: app_id,
            redirectUrl: redirect_url,
        });

        const oneTap = new VKID.OneTap();
        oneTap.render({
            container: document.getElementById('vk-oauth') as HTMLElement,
        });

        // Функция очистки
        return () => {
            oneTap.close();
        }
    }, []);
`
