### ISSUE TITLE
[Doc]: https://id.vk.com/about/business/go/docs/en/vkid/latest/vk-id/connection/web/onetap

### ISSUE THREAD

**Issue by ZiziNauchFilm** [VKCOM/vkid-web-sdk#23]
##############################################################################
Установил VK ID SDK c помощью скрипта - в head прописано:
<script src="https://unpkg.com/@vkid/sdk@2.1.0/dist-sdk/umd/index.js"></script>
/*также пробовал все то же, но @vkid/sdk@2.0.0 */

##############################################################################
Далее хочу сделать авторизацию по кнопке One Tap.

##############################################################################
Добавил на страницу такой div
div id="VkIdSdkOneTap"

и такой скрипт
const VKID = window.VKIDSDK;

VKID.Config.init({
  app: 52056694,
  redirectUrl: "https://misharepet.com/vkauth",
  state: 'dj29fnsadjsd82',
  codeVerifier: 'xhM4i-5hj6Q09YRNrVkmLaBVMOJs4P59AziaiAWwf-I',
  scope: 'email phone',
  mode: VKID.ConfigAuthMode.InNewTab
});

const oneTap = new VKID.OneTap();

const container = document.getElementById('VkIdSdkOneTap');

if (container) {
  oneTap.render({ container: container, scheme: VKID.Scheme.LIGHT, lang: VKID.Languages.RUS })
  .on(VKID.WidgetEvents.ERROR, ()=>{})
}

##############################################################################
##############################################################################
Кнопка отрисовывается.
Но при нажатии не появляется окно, где пользователь даст разрешения.
А редирект происходит сразу.
**ЭТО ВОПРОС № 1. ПОЧЕМУ НЕ ПОКАЗЫВАЕТСЯ ФОРМА, ГДЕ ПОЛЬЗОВАТЕЛЬ ДАЕТ РАЗРЕШЕНИЯ?**

Но я все же получаю в ответе code, state и device_id.
И пробую обменять их на access token.
Т.к. я передавал codeVerifier в блоке VKID.Config то я следую инструкции:
ваш сервис передал в SDK codeVerifier — код подтверждения можно обменять на токены с помощью метода SDK VKID.Auth.exchangeCode(code, device_id) или через вызов id.vk.com/oauth2/auth, где grant_type = authorization_code.

Но выполнение запроса id.vk.com/oauth2/auth (со всем параметрами типа grant_type) происходит с ошибкой.
**ЭТО ВОПРОС № 2. ПОЧЕМУ НЕ ВЫПОЛНЯЕТСЯ ЗАПРОС id.vk.com/oauth2/auth?**

**Comment by mclaran** [comment]
@ZiziNauchFilm Здравствуйте, не могли бы Вы уточнить по второму вопросу, какая именно происходит ошибка? можете ли приложить скрин/видео с кейсом, а так же пример для воспроизведения?

**Comment by ZiziNauchFilm** [comment]
Добрый день!
Все вопросы снимаются, извините за беспокойство.

По вопросу формы разрешения доступа: сразу не обратил внимание, что у кнопки есть параметр fastAuthEnabled. (+в том окне, что появляется, список разрешений внизу мелкой ссылкой, а в других видах они более явно были и это смутило).

По 2 вопросу, судя по всему, я сам запутался когда и кому передавать code_verifier и code_challenge. 

Еще раз спасибо за уделенное внимание)
